name: "nakama1"
database:
  address:
    - "root@cockroachdb:26257"

console:
  max_message_size_bytes: 409600

logger:
  level: "DEBUG"

runtime:
  js_entrypoint: "build/index.js"

session:
  token_expiry_sec: 7200 # 2 hours

socket:
  max_message_size_bytes: 4096
  max_request_size_bytes: 131072

metrics:
  prometheus_port: 9100
